- name: demo on play level vafriables
  hosts: localhost
  connection: local
  vars:
    COURSE: "Ansible"
    Trainer: "Shiva"
    DURATION: "150HRS"

  tasks:
  - debug:
      msg: "Hi, I am learining {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}
