- name: demo on task level vafriables
  hosts: local
  connection: local
  vars: 
    COURSE: "Ansible"
    TRAINER: "Shivakumar"
    DURATION: "10MIN"

  tasks:
  - name: JAYASRI print information
    vars:
      COURSE: "Devops with Aiops"
    debug:
      msg: "Hi, I am learning {{ COURSE }}, trainer is {{ TRAINER }}" 

  - name: VINOD print information
    vars:
      COURSE: "Devops with Aiops"
      TRAINER: "AAYANSH"
    debug:
      msg: "Hi, I am learning {{ COURSE }}, trainer is {{ TRAINER }}" 

 